/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pair.scheduler;

import java.io.FileReader;
import java.io.FileWriter;

public class App {

    public static void main(String[] args) {
        try(FileReader input = new FileReader(args[0]);
            FileWriter output = new FileWriter(args[1]);) {
            
            SchedulerInputParser parser = new SchedulerInputParser(input, output);
            parser.process();
            output.flush();

        } catch (Exception e) {
            System.out.println("An error has occured");
            System.out.println(e.getMessage());
        }
    }
}
